sudo: false
dist: trusty

cache:
  apt: true

git:
  depth: false

addons:
  apt:
    packages:
      - python-pip
      - libalgorithm-diff-perl
      - graphviz

language: python
python:
  - "2.7"
install:
 - "pip install -r doc/requirements.txt"
script:
  - bash openpower/scripts/update-defconfigs.sh
  - cd doc/; make html

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  local_dir: "doc/_build/html"
  on:
    branch: master
